services:
  web:
    build: ./
    command: uvicorn web.app:app --host 0.0.0.0 --port 8000 --workers 1
    restart: always
    env_file:
      - .env.db
      - .env.redis
    environment:
      - DB_HOST=db
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine3.20
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:7.2.5
    restart: always
    expose:
      - "6379"
    env_file:
      - ./.env.redis

  worker:
    build: ./
    command: python3 -m celery -A web.worker.celery worker --loglevel=info --concurrency=1
    volumes:
      - ./:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data: