services:
  web:
    build:
      dockerfile: Dockerfile.dev
    command: uvicorn web.app:app --host 0.0.0.0 --port 8000 --workers 1 --reload
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
      - media:/usr/src/app/media

  db:
    image: postgres:alpine3.20
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:7.2.5
    restart: always
    expose:
      - "6379"
    env_file:
      - ./.env.redis

  worker:
    build:
      dockerfile: Dockerfile
    command: python3 -m celery -A web.worker.celery worker --loglevel=info --concurrency=1
    restart: always
    volumes:
      - media:/usr/src/app/media
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  media:
