services:
  db:
    image: postgres:alpine3.20
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./.env.redis

  worker:
    build: ./
    command: python3 -m celery -A web.worker.celery worker --loglevel=info --concurrency=1
    volumes:
      - ./:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data: