version: '3.8'

services:
  db:
    image: postgres:alpine3.20
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./.env.redis

volumes:
  postgres_data: